### ISSUE TITLE
clone后直接build是不行的

### ISSUE THREAD

**Issue by Cities2000** [laodaobazi/ldbz-shop#1]
文档没有描述对于中央仓库和阿里仓库没有的架包如何处理，例如fastdfs

**Comment by laodaobazi** [comment]
使用阿里仓库，
<mirror>
      <id>alimaven</id>
      <name>aliyun maven</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
      <mirrorOf>central</mirrorOf>        
    </mirror>
原本打算将商品图片放到fastdfs中，后来偷懒，图省事直接把图片上传到硬盘了，通过nginx做动静分离进行展现。你再更新一下代码吧，已经将fastdfs去掉了，目前尚未使用fastdfs。
